### ISSUE TITLE
Revise Matching method 

### ISSUE THREAD

**Issue by f-rakete** [rs1991/PropertyRental#1]
https://github.com/rs1991/PropertyRental/blob/e5dfb541d42579ad3174939f6fee89557f284d43/PropertyRental/LogicMethods.cs#L667-L703

why is this so inconsistent? one condition is a `continue`, the other ones set the boolean flag

` if(tenant.Smoker != home.SmokingAllowed)`

if the tenant is a  smoker  and smoking is not allowed you skip

what happens if the tenant is a nonsmoker and smoking is allowed, shouldnt that be a match as well?

` if(tenant.BedRoomsRequired != home.BedRooms)`

if i require 4 bedrooms, and the flat has 6 bedrooms, it is still relevant to me

etc.

**Comment by f-rakete** [comment]
@rs1991 if this issue is fixed please close it

**Comment by rs1991** [comment]
Both conditions changed. If a tenant is not a smoker then they can be matched with a home where smoking is allowed. For the bedrooms, it now checks to make sure that homes with more bedrooms can be displayed if other conditions are met. 

if(tenant.Smoker != home.SmokingAllowed && tenant.Smoker == true)
                {
                    isMatch = false;
                }

if(tenant.BedRoomsRequired > home.BedRooms)
                {
                    isMatch = false;
                }
