### ISSUE TITLE
Logic seems to be not working

### ISSUE THREAD

**Issue by f-rakete** [rs1991/PropertyRental#2]
https://github.com/rs1991/PropertyRental/blob/f0968baa79250fba6a9f8a0a0a40ad212f038e9a/PropertyRental/LogicMethods.cs#L727-L730

**Comment by rs1991** [comment]
@f-rakete I have changed the logic so that a tenant who is not a smoker is rewarded with points but a tenant who is a smoker, will only get the points if the home also allows smoking.

**Comment by f-rakete** [comment]
@rs1991 if the issue is resolved you can close it 😊

**Comment by f-rakete** [comment]
if you use the  github desktop client, you can also put a reference here in your commit message with the # sign #2
