### ISSUE TITLE
Make Budget Points dynamic

### ISSUE THREAD

**Issue by f-rakete** [rs1991/PropertyRental#3]
https://github.com/rs1991/PropertyRental/blob/f0968baa79250fba6a9f8a0a0a40ad212f038e9a/PropertyRental/LogicMethods.cs#L739-L742

also this shouldnt be just "30" we talked about that on the call

how about something like budget/price * 100

**Comment by rs1991** [comment]
A calculation is included if the home falls within the tenant's budget.
